import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import { MuiSetup } from '../../utils/MuiSetup'
import { SessionProvider } from 'next-auth/react';
import { Session } from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,
  session: Session | null

}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {session ? (
          <SessionProvider session={session}>
            <MuiSetup>{children}</MuiSetup>
          </SessionProvider>
        ) : (
          <MuiSetup>{children}</MuiSetup>
        )}
      </body>
    </html>
  )
}
